version: "3.8"
services:
  express-app:
    container_name: server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: s-dev
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: 'admin'
      DB_PASSWORD: 'letmein'
      DB_NAME: moviesdb
      DB_CONNECTION_LIMIT: 20
      SERVICE_NAME: express-app
      SERVER_PORT: 3000
    volumes:
      - ./server:/app
      - servermodules:/app/node_modules
      - /app/node_modules
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - internalnet
    depends_on:
      - mysql
  mysql:
    container_name: db
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: moviesdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    image: mysql:8.0.35
    volumes:
      - my-datavolume:/var/lib/mysql
    networks:
      - internalnet
volumes:
  servermodules: {}
  my-datavolume:
networks:
  internalnet:
    driver: bridge
