version: "3.8"
services:
  express-server:
    container_name: server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: s-dev
    volumes:
      - ./server:/app
      - servermodules:/app/node_modules
      - /app/node_modules
    ports:
      - "8080:3000"
  mysql:
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DB=my_store
      - MYSQL_USER=byance
      - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306"
    image: mysql:8.0.35
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  servermodules: {}
  my-datavolume: